### ISSUE TITLE
Distribute the generated .c files on PyPI

### ISSUE THREAD

**Issue by betatim** [scikit-garden/scikit-garden#31]
[distributing cython modules](http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules) outlines a nice way to distribute the `.c` files via PyPI and removes the need for the user to install `cython`. I think they even recommend doing this.

One caveat: not sure how much of this is true if you build manylinux wheels (#19)?

**Comment by MechCoder** [comment]
Hmm. Seems like the package on PyPi already has c files in them, that is it is already distributed (https://pypi.python.org/pypi/scikit-garden/)
