### ISSUE TITLE
error of import MondrianForestRegressor

### ISSUE THREAD

**Issue by vatn** [scikit-garden/scikit-garden#32]
Hello,
I have succeeded to install scikit-garden, but when I tried to "import" :

from skgarden import MondrianForestRegressor

There was always an error : 
ModuleNotFoundError: No module named 'skgarden.mondrian.tree._criterion'

I didn't understand this error, so, can you please help me?

**Comment by MechCoder** [comment]
How did you install it?

**Comment by vatn** [comment]
I use anaconda 3 and install it by : 
pip install setuptools numpy scipy scikit-learn cython
pip install scikit-garden

**Comment by vatn** [comment]
Sorry, I think it is ok now. I used the code of "scikit-garden 0.1", which is released  on May 20,  and repeat the install procedure, it seems ok now. Thank you so much.

**Comment by MechCoder** [comment]
great, thanks!
