### ISSUE TITLE
Question about partial_fit

### ISSUE THREAD

**Issue by vatn** [scikit-garden/scikit-garden#34]
Hi,

I tested mondrian forest online learning with titanic dataset in kaggle, but I have met an error as following:
I firstly separated the dataset into train set and test set.

```
titanic = pd.read_csv('train_cleaned.csv')
y = titanic['Survived'].values
train,test = train_test_split(titanic,random_state=10, stratify=y, test_size=0.2)  
```

Then I used always test set for validating the performance and train set to train the model.
I then separated the train set into base and new set . I fitted  "base set" firstly, then I continued to update the model  with each data point in the new set: 

```
#test for datapoints
base, new = np.split(train.sample(frac=1), [int(.8*len(train))])


clf_dp = MondrianForestClassifier(random_state=0,n_estimators=1,min_samples_split=9,max_depth=20)
clf_dp.fit(base.drop('Survived',axis=1).values,base['Survived'].values)

x = new.drop('Survived',axis=1)
y = new['Survived']

for index,row in new.iterrows():
    print(y[index])
    clf_dp.partial_fit(x.loc[index].values.reshape(1,-1),np.array([y[index].astype(int)]))
    print('succeed')
```
  
But in the first iteration, it succeeded to update, however, in the second iteration, an error occurred:

```
1
succeed
0

---------------------------------------------------------------------------
ValueError  
C:\Anaconda2\envs\py3k\lib\site-packages\sklearn\preprocessing\label.py in transform(self, y)
    151         if len(np.intersect1d(classes, self.classes_)) < len(classes):
    152             diff = np.setdiff1d(classes, self.classes_)
--> 153             raise ValueError("y contains new labels: %s" % str(diff))
    154         return np.searchsorted(self.classes_, y)
    155 

ValueError: y contains new labels: [0]
```

Did I correctly use these function?
Can you please help me to solve it?
Thanks!

**Comment by MechCoder** [comment]
Sorry for the delay in replying.

While calling `partial_fit` if the first batch does not contain all the elements, then you should provide the total number of classes in the entire training data as the third argument, This is in consistency with sklearn handling of `partial_fit`.

Your code should work this way:

```python
classes = np.unique(y)
for index,row in new.iterrows():
    print(y[index])
    if index == 0:
        clf_dp.partial_fit(x.loc[index].values.reshape(1,-1),np.array([y[index].astype(int)]), classes=classes)
    else:
        clf_dp.partial_fit(x.loc[index].values.reshape(1,-1),np.array([y[index].astype(int)]))
    print('succeed')
```

This is documented here (https://github.com/scikit-garden/scikit-garden/blob/master/skgarden/mondrian/ensemble/forest.py#L69) let me know if I can make it more clear?
