### ISSUE TITLE
fmin, fmax don't work on Windows in Python 2.7

### ISSUE THREAD

**Issue by dougalsutherland** [scikit-garden/scikit-garden#41]
`libc.math.{fmin,fmax}`, used in [`mondrian.tree._tree`](https://github.com/scikit-garden/scikit-garden/blob/d6c3d6d9c15f3fc8c959018dc3ff532fb5193eee/skgarden/mondrian/tree/_tree.pyx), are C99 functions that [don't work in old Visual Studio versions](https://stackoverflow.com/questions/40737873/fmax-and-fmin-alternative-in-c89) like the one you need to use to build Python 2.7 extensions. So the build fails with a linker error on Windows for 2.7; [example build log](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.15318/job/k3f7ws3wo3vk40wh) from https://github.com/conda-forge/staged-recipes/pull/3352.

Probably the easiest thing to do is to write little helper functions, e.g.
```python
cdef inline double fmax(double left, double right):
    return left if left > right else right

cdef inline double fmin(double left, double right):
    return left if left < right else right
```
and either figure out how to only use them on Windows or just always use them.

**Comment by MechCoder** [comment]
Great, thanks a lot! Would you have time to send a pull request?

(Though it must be noted that neither do tests run on Python 2.7 nor on a Windows environment)
