### ISSUE TITLE
setup failure on Windows: path cannot be absolute

### ISSUE THREAD

**Issue by dougalsutherland** [scikit-garden/scikit-garden#48]
For example, here: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.16558/job/k1u8dc61iq2n4pmk#L493

I don't have a Windows machine, but when I build locally on Linux/Mac, my `scikit_garden.egg-info/SOURCES.txt` includes absolute paths to `numpy/core/include/numpy/{array,ufunc}object.h`. This then breaks inside [`distutils.util.convert_path`](https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/distutils/util.py#L111), which is a no-op on Linux/Mac but says that paths can't be absolute on Windows.

I think this is probably related to something about the recursive build setup using numpy.distutils (e.g. #23), but I'm not totally sure.

**Comment by dougalsutherland** [comment]
Should be fixed by #49.

**Comment by evhub** [comment]
@dougalsutherland Do you have an ETA on when the fix for this will be released?

**Comment by dougalsutherland** [comment]
@evhub I'm not involved with the project, sorry. You should be able to install from source with just `pip install git+https://github.com/scikit-garden/scikit-garden/`, though.
