### ISSUE TITLE
Importing scikit-garden in requirements.txt

### ISSUE THREAD

**Issue by paulVelthuisBoskabouter** [scikit-garden/scikit-garden#61]
I want to pre-install scikit-garden vai a requirements.txt
To make it future proof I would like to import it with a version such as:
numpy==1.13.3
How can I do this for scikit-garden?

When installing I get the following error:
    ImportError: ('No module named Cython', 'Please install cython with a version >= 0.23 in order to build a scikit-garden development version.')

**Comment by dougalsutherland** [comment]
You should also put a `Cython` dependency in the `requirements.txt`. That might or might not work; related to https://github.com/scikit-garden/scikit-garden/issues/23. If you separately install cython beforehand, it should definitely work.

**Comment by paulVelthuisBoskabouter** [comment]
That solved it :)
