### ISSUE TITLE
Support for Enum-Encoding as in H2o

### ISSUE THREAD

**Issue by dnks23** [scikit-garden/scikit-garden#68]
Hello,

the H2o ML Framework supports an enum-encoding scheme. It would be nice to have this for sklearn as well. As far as I know there are no contributions made to add this for sklearn models.

This would be useful to handle categorical features and find the best split for categorical features. There is also an implementation of this in LightGBM: [Read Section about optimal split for categorical features](https://lightgbm.readthedocs.io/en/latest/Features.html#optimal-split-for-categorical-features)

Anyone has thoughts about this?

**Comment by betatim** [comment]
It sounds like you want to make additions to https://github.com/scikit-learn/scikit-learn and not scikit-garden. You should file your issue there I think.
